spring:
  datasource:
    generateUniqueName: false
    name: tacocloud
  data:
    rest:
      basePath: /data-api
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
